services:
  mysql:
    image: mysql:8.0
    container_name: sava_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sava_db
      MYSQL_USER: sava_user
      MYSQL_PASSWORD: sava_pass
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  adminer:
    image: adminer:latest # Imagem mais leve
    container_name: sava_adminer
    restart: always
    ports:
      - "8081:8080" # A porta interna do Adminer é 8080
    depends_on: # Garante que o mysql inicie antes
      - mysql