version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: sava_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sava_db
      MYSQL_USER: sava_user
      MYSQL_PASSWORD: sava_pass
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sava_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
